### PR TITLE
3.0.alpha6 release

### PR DESCRIPTION
**Pull request by Pandrex247**
Tag provisionally pushed: https://github.com/payara/ecosystem-arquillian-connectors/tree/3.0-alpha6

### CODE REVIEW

**Review by pdudits — APPROVED** [review]

**Comment by Pandrex247** [comment]
Tag updated

**Comment by Pandrex247** [comment]
Staged ready for release: fishpayara-2079

**Comment by Pandrex247** [comment]
Tag updated again with commit to set client-ee9 pom version to 3.0.alpha6

**Comment by Pandrex247** [comment]
Restaged: fishpayara-2080

**Pull request merged**
